 headers1 = {
        "Referer": "http://www.weather.com.cn/weather1d/{}.shtml".format(city_id),
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                      'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
    }
    HTML = "https://tianqi.2345.com/pudong1d/71146.htm"

    response1 = requests.get(HTML, headers=headers1)
    response1.encoding = "utf-8"
    my_soup = BeautifulSoup(response1.text, "html.parser")

    # 获取信息主标签
    main_str = my_soup.find("div", attrs={"class": "real-mess"})

    # 获取今天天气、温度
    # weather_main = main_str.find("div", attrs={"class": "real-today"})
    # split = weather_main.text.split("：")[1]
    # # 今天天气
    # weather = split.split("° ")[1]
    # # 最高气温
    # temp = split.split("° ")[0].split("-")[1] + "°C"
    # # 最低气温
    # tempn = split.split("° ")[0].split("-")[0] + "°C"

    # 现在的天气 多云
    now_weather = main_str.find("em", attrs={"class": "cludy"}).text
    find_all = main_str.findAll("span", attrs={"class": "real-data-mess fl"})
    # 当前风向 东北风3级
    wind_direction = find_all[0].text.replace(' ', '')
    # 当前空气湿度 86%
    air_humidity = find_all[1].text.replace('湿度 ', '')
    # 当前紫外线  很弱
    ultraviolet_rays = find_all[2].text.replace('紫外线 ', '')

    # 空气主要标签
    air_main = my_soup.find("div", attrs={"class": "box-mod-tb"})
    # 空气质量  优-16
    air_quality = air_main.find("em").text + "-" + air_main.find("span").text
    # pm 2.5    10
    pm = air_main.find("div", attrs={"class": "aqi-map-style-tip"}).find("em").text

    hours24_main = my_soup.find("div", attrs={"class": "hours24-data-th-right"})
    # 日出时间  06:01
    sunrise = hours24_main.findAll("span")[0].text.split(" ")[1]
    # 日落时间  19:00
    sunset = hours24_main.findAll("span")[1].text.split(" ")[1]
